indent_type = "Spaces"     # Use spaces instead of tabs (matches expandtab)
indent_width = 2           # Match Neovim's shiftwidth, tabstop, and softtabstop
column_width = 120         # Match Neovim's textwidth = 100
no_call_parentheses = true # Omit parentheses in function calls when possible
